# Generated by Django 5.0.4 on 2024-07-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
    ]
