# Generated by Django 5.0.4 on 2024-07-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
    ]
