# Generated by Django 5.0.4 on 2024-08-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivrariaAutor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'livraria_autor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LivrariaCategoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'livraria_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LivrariaLivro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='livros/')),
                ('ano', models.IntegerField()),
                ('valor', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'livraria_livro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LivrariaLivroAutor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'livraria_livro_autor',
                'managed': False,
            },
        ),
    ]
